### ISSUE TITLE
API Gateway does not work immediately in China regions

### ISSUE THREAD

**Issue by lazurey** [aws-samples/amazon-api-gateway-mutating-webhook-for-k8#2]
After deploying `api-gateway.yaml` stack, although the API Gateway and Lambda function is created successfully, the API is not accessible in `cn-north-1` and `cn-northwest-1`.

Reference:
1. https://forums.aws.amazon.com/thread.jspa?messageID=872418
2. https://github.com/serverless/serverless/issues/4703

Since in `mutating-webhook.yaml` the failure policy is configured to `Ignore`, there won't be any errors, I can only find the image is not replaced.
If configured to `Faill`, the pods won't be deployed or updated.

**How to reproduce**  

1. Create stack using `api-gateway.yaml` in `cn-northwest-1`
  (may need to update line 118, to `- !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"`)
2. copy the output and use Postman to `POST` this API, you will get
```json
{
    "Message": null
}
```
3. If continue with the steps 3 and 4, you will see the image is not replaced.
4. And check `kubectl get events`, you should be able to find a message like `Error creating: Internal error occurred: failed calling webhook "image.mutating.webhook": unknown`

**Temporary solution**  

1. Create the api gateway stack in other regions and do not set any permissions.
2. Use the output to continue in `cn-north-1` and `cn-northwest-1`

**Comment by walkley** [comment]
@lazurey Thanks for pointing out this issue. Just a little bit confusing, as you said in those reference links, it is a business process issue which need to whitelist the account in AWS China regions, then API GW can be accessed. Can you please clarify your requirements here?

**Comment by lazurey** [comment]
> Just

It took me a day to dig out and find out this reason. Hopefully no one else wastes more time on it.

So if possible, maybe add a hint for users in `cn-north-1` and `cn-northwest-1`, this guide won't work for them, or what could go wrong for these 2 regions.
